[package]
name = "spade"
version = "1.8.0"
authors = ["Stefan Altmayer <stoeoef@gmail.com>"]
description="Spatial datastructures like r-trees and delaunay triangulations for rust."
documentation = "https://docs.rs/spade/"
repository = "https://github.com/Stoeoef/spade"
readme = "README.md"
keywords = ["delaunay", "triangulation", "rtree", "geometry", "interpolation"]
license = "MIT/Apache-2.0"
edition = "2018"

[features]
serde_serialize = ["num/serde", "serde"]

[dependencies]
cgmath = ">=0.10.0, <=0.17.*"
nalgebra = ">=0.11.0, <=0.18.*"
num = ">= 0.1.0, <=0.2.*"
clamp = "0.1.*"
smallvec = "0.6.*"
pdqselect = "0.1.*"
serde_derive = { version = "1.0", optional=true }
serde = { version = "1.0", optional=true, features=["rc", "serde_derive"] }

[dev-dependencies]
rand = "0.5.*"
serde_json = "1.0"
approx = "0.2.*"

[dev-dependencies.cgmath]
version = "<=0.17.*"
features = ["serde"]

[profile.bench]
opt-level = 3
debug-assertions = false

[badges]
maintenance = { status = "passively-maintained" }
